name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install --immutable

      - name: Rodar Lint
        run: yarn lint

      - name: Rodar Testes
        run: yarn test

